import React, { useState } from "react";
import classes from "./Info.module.scss";

const Info = () => {
  const [faqs, setFaqs] = useState([
    {
      question: "What can be the estimated average APY?",
      answer: "The estimated average APY can range from 15–25% up to 40–60% based on current liquidity mining yields.",
    },
    {
      question: "How is the 50% tax distributed and used? Who will be the beneficiary and why not tax 100%?",
      answer: "The collected tax goes towards the ESIR-USDC LP and buyback allocation. The 50% tax might be a reasonable threshold for speculative participants to still purchase ESIR without staking EBONDS and providing a significant premium to flow into the Protocol-Owned Liquidity — PoL. Same applies for EBONDS TAX.",
    },
    {
      question: "Is there a way to cash out EBONDS besides selling them on the open market peer-to-peer?",
      answer: "Yes, EBONDS can be cashed out through the EBONDS Selling contract, which provides liquidity equivalent to 10% of the Total Value Locked (TVL) and applies a 10% tax. Once the decentralized peer-to-peer (P2P) marketplace is launched, EBONDS holders can sell and arbitrage their holdings without the 10% tax applied by the Protocol-Owned Liquidity (PoL). The market price of EBONDS is expected to establish itself between $0.91 (above the price at which the tax is applied by the selling contract) and $0.99 (below the price at which the buying contract is executed). The ongoing yield and fees generated will be rebalanced into the EBONDS Selling contract and later into the P2P marketplace, which will help maintain ongoing liquidity and demand to support the price of EBONDS.",
    },
    {
      question: "What is the reason for the difference in tax rates on EBONDS and ESIR?",
      answer: "EBONDS is real collateral that is utilized to generate yields & fees and must be deployed. Exiting before any long-term commitment should be penalized until the P2P marketplace is deployed. During this transition period, we reserve 10% of liquidity for those who wish to exit with a 10% tax. On the other hand, ESIR tokens start with a small reserve of collateral, and as they are gradually distributed, the strategies start earning yield and fees, which back and provide liquidity towards ESIR tokens. The equivalent analogy would be dividend distributions, and every participant can sell their rewards to claim and realize earned profits with no tax implications. The tax on the buying of the tokens reduces the temptation for users/speculators to mass buy ESIR tokens cheap and then take out liquidity in the future that was intended for real participants to cash out. In other words, it ensures that people supporting the community early on will not have the percentage of their platform interest diluted by a large whale in the future. It gives an equal playing field to community support.",
    },
    {
      question: "Is there a way to cash out EBONDS besides selling them on the open market peer-to-peer?",
      answer: "Yes, EBONDS can be cashed out through the EBONDS Selling contract, which provides liquidity equivalent to 10% of the Total Value Locked (TVL) and applies a 10% tax. Once the decentralized peer-to-peer (P2P) marketplace is launched, EBONDS holders can sell and arbitrage their holdings without the 10% tax applied by the Protocol-Owned Liquidity (PoL). The market price of EBONDS is expected to establish itself between $0.91 (above the price at which the tax is applied by the selling contract) and $0.99 (below the price at which the buying contract is executed). The ongoing yield and fees generated will be rebalanced into the EBONDS Selling contract and later into the P2P marketplace, which will help maintain ongoing liquidity and demand to support the price of EBONDS.",
    },
    {
      question: "Why using a native reward token instead of USDC or ETH?",
      answer: "Using a native reward token has several advantages over using stablecoins like USDC or cryptocurrencies like ETH. For one, it creates a fair playing field for users to employ various investment strategies. Holding the native token for the long-term can result in compounding rewards generated by the collateral, which can then lead to price appreciation. Patient holders can also benefit when other users cash out, leading to a tighter supply and higher demand. Additionally, using a native token allows users to support the protocol and ensure that liquidity remains on the Collateralized Investment Strategy instead of flowing into the Protocol Owned Liquidity Side. The distribution of the token is also organic, as it is based on the behavior of all participants. This provides opportunities for cheap buybacks and adding liquidity, which can gradually increase the token’s price over time. Lastly, the distribution of the native token is backed by the rewards and yields generated by the EBONDS collateral held to generate the rewards. This ensures that the token has a tangible asset backing its value and can help prevent hyperinflation.",
    },
    {
      question: "How does the rebalancing work?",
      answer: "The rebalancing process is executed by refilling the lowest allocations with rewards and yields generated. The priority is given to Protocol-owned Liquidity. Rebalancing first into the Selling EBONDS SmartContract and ESIR-USDC LP, and buybacks. This ensures participants have exit liquidity on EBONDS and ESIR Tokens. Then rebalancing goes into the Collateralized Investment Strategies to strengthen the positive flywheel effect and cover potential Impermanent Loss. Scaling both allocations will lead to more yield & fees for the same participants.",
    },
    {
      question: "How is the APY calculated?",
      answer: "The APY for ESIR Rewards is calculated based on the fixed and steady rewards of ESIR Token distribution, which are earned by users contributing collateral and staking EBONDS. The rewards are equal and fair among participants. The issuing is fixed, so the only variable affecting APY is the ESIR price, which reflects the APY. A higher ESIR price corresponds to a higher APY. While the current APY may be low, as the collateral grows and generates more rewards and yields, the APY will increase. As an example, earning ESIR tokens at a 15% APY today, only means that if you were to sell your rewards, you would earn an average 15% APY on your EBONDS contribution. No matter what is the current APY, everyone always earns the exact same amount of ESIR Tokens. +-1ESIR per day per 1.000#EBONDS Staked. However, with the organic behavior of short, medium, and long-term holders and the flywheel effect that takes time to scale, the value of those earned ESIR tokens should rise over time, leading to a much higher effective APY. For instance, someone who earned rewards at a 15% APY for 11 months and then cashes out when the APY increases to 20% will have earned an effective APY of 20%, whereas those who sold earlier will have earned only 15%.",
    },
    {
      question: "Considering the max supply of EBONDS is 7.000.000#, what happens if the underlying collateral goes above 7.000.000$? Will all the surplus go to the ESIR price appreciation and apy distribution?",
      answer: "If the full supply enters in circulation there wont be any EBONDS left on the buy contract and this removes the 1$ top limit. Main goal is exactly to get surplus to have a floating positive NAV to earn a reasonable yield and fees in future market conditions and stay fully real asset backed. Transferring every excess NAV to ESIR/apy could lead to under collateralization in the future. Sticking to the core block allocations will scale all blocks and we can let participants decide what is the fair valuation on the free market. Example of 7M$ TVL and the 10% Eth, would be 700k$ NAV, if overall NAV grows to 8M$ this allocation will be capped to 800k$. Natural valuation of EBONDS would be 1.14$ (8/7). However, if users cash out ESIR, rebalancing will feed back yield and fees into the PoL. Collateralized Investment Strategies only rebalance internally in NAV measures to avoid dilution and boost the flywheel effect of NAV growth and increase in yield and fees generated. Natural equilibrium will be met between different users. Do they expect crypto in general to go up or down, some will hodl with diamond hands, others will speculate and attempt to time markets and others will cash out and expose to other markets. In general, with the tax, P2P, tokenomics and rules, the main goal is to reward the community with a growing apy distribution, achieved with the growing NAV and considering the fair price of 1$ for EBONDS. Who will buy above is paying a premium and rewarding early adopters who want to exit. To sum up, ESIR valuation is expected to grow, but not directly from NAV rebalancing (dilution) from the Collateralized Investment Strategies into the Protocol-owned Liquidity, but from the flywheel effect of the NAV growing and generating higher volume in yield & fees that can now rebalance into the PoL.",
    },
  ]);

  const toggleAccordion = (index) => {
    setFaqs((prevFaqs) =>
      prevFaqs.map((faq, i) =>
        i === index ? { ...faq, isOpen: !faq.isOpen } : { ...faq, isOpen: false }
      )
    );
  };

  return (
    <div className={classes.Info}>
      <div className={classes.accordion}>
        {faqs.map((faq, index) => (
          <div key={index} className={classes.faq}>
            <div className={classes.question} onClick={() => toggleAccordion(index)}>
              {faq.question}
            </div>
            {faq.isOpen && <div className={classes.answer}>{faq.answer}</div>}
          </div>
        ))}
      </div>
    </div>
  );
};

export default Info;
