export const SEND_STRIPE_CHARGE = 'SEND_STRIPE_CHARGE';
export const SEND_STRIPE_CHARGE_SUCCESS = 'SEND_STRIPE_CHARGE_SUCCESS';
export const SEND_STRIPE_CHARGE_FAIL = 'SEND_STRIPE_CHARGE_FAIL';
export const SEND_STRIPE_CUSTOMER_CREATE = 'SEND_STRIPE_CUSTOMER_CREATE';
export const SEND_STRIPE_CUSTOMER_CREATE_SUCCESS =
    'SEND_STRIPE_CUSTOMER_CREATE_SUCCESS';
export const SEND_STRIPE_CUSTOMER_SUBSCRIBE = 'SEND_STRIPE_CUSTOMER_SUBSCRIBE';
export const SEND_STRIPE_CUSTOMER_SUBSCRIBE_SUCCESS =
    'SEND_STRIPE_CUSTOMER_SUBSCRIBE_SUCCESS';
