export const GET_WAITLIST_STATE = 'GET_WAITLIST_STATE';
export const GET_WAITLIST_STATE_SUCCESS = 'GET_WAITLIST_STATE_SUCCESS';
export const GET_EARLY_ACCESS_REQUEST = 'GET_EARLY_ACCESS_REQUEST';
export const GET_EARLY_ACCESS_REQUEST_SUCCESS =
    'GET_EARLY_ACCESS_REQUEST_SUCCESS';
